# app/job_matching/knowledge/knowledge_data.py
"""
Static knowledge data for recruitment and job matching.
Contains salary benchmarks, skill trends, and industry standards.
FIXED: Added Python-specific keywords and backend developer data.
"""

RECRUITMENT_KNOWLEDGE = {
    "salary_benchmarks": {
        "software_engineer": {
            "junior": {"min": 45000, "max": 65000, "avg": 55000},
            "mid": {"min": 65000, "max": 95000, "avg": 80000},
            "senior": {"min": 95000, "max": 150000, "avg": 120000},
        },
        "backend_developer": {  # ADDED: Backend developer salaries
            "junior": {"min": 45000, "max": 65000, "avg": 55000},
            "mid": {"min": 65000, "max": 90000, "avg": 77000},
            "senior": {"min": 90000, "max": 140000, "avg": 115000},
        },
        "python_developer": {  # ADDED: Python-specific salaries
            "junior": {"min": 48000, "max": 68000, "avg": 58000},
            "mid": {"min": 68000, "max": 95000, "avg": 81000},
            "senior": {"min": 95000, "max": 145000, "avg": 120000},
        },
        "data_scientist": {
            "junior": {"min": 55000, "max": 75000, "avg": 65000},
            "mid": {"min": 75000, "max": 105000, "avg": 90000},
            "senior": {"min": 105000, "max": 170000, "avg": 135000},
        },
        "product_manager": {
            "junior": {"min": 60000, "max": 80000, "avg": 70000},
            "mid": {"min": 80000, "max": 120000, "avg": 100000},
            "senior": {"min": 120000, "max": 180000, "avg": 150000},
        },
        "frontend_developer": {
            "junior": {"min": 40000, "max": 60000, "avg": 50000},
            "mid": {"min": 60000, "max": 85000, "avg": 72000},
            "senior": {"min": 85000, "max": 130000, "avg": 107000},
        },
        "devops_engineer": {
            "junior": {"min": 50000, "max": 70000, "avg": 60000},
            "mid": {"min": 70000, "max": 100000, "avg": 85000},
            "senior": {"min": 100000, "max": 160000, "avg": 130000},
        },
        "marketing_manager": {
            "junior": {"min": 40000, "max": 55000, "avg": 47000},
            "mid": {"min": 55000, "max": 80000, "avg": 67000},
            "senior": {"min": 80000, "max": 120000, "avg": 100000},
        },
    },
    "skill_demand": {
        "programming": {
            "python": {
                "demand": "very_high",
                "growth": "15%",
                "difficulty": "medium",
                "salary_impact": "20%",
            },
            "javascript": {
                "demand": "very_high",
                "growth": "10%",
                "difficulty": "medium",
                "salary_impact": "15%",
            },
            "react": {
                "demand": "high",
                "growth": "20%",
                "difficulty": "medium",
                "salary_impact": "18%",
            },
            "node.js": {
                "demand": "high",
                "growth": "12%",
                "difficulty": "medium",
                "salary_impact": "12%",
            },
            "aws": {
                "demand": "very_high",
                "growth": "25%",
                "difficulty": "high",
                "salary_impact": "30%",
            },
            "docker": {
                "demand": "high",
                "growth": "18%",
                "difficulty": "medium",
                "salary_impact": "15%",
            },
            "kubernetes": {
                "demand": "high",
                "growth": "30%",
                "difficulty": "high",
                "salary_impact": "25%",
            },
            "java": {
                "demand": "high",
                "growth": "5%",
                "difficulty": "medium",
                "salary_impact": "10%",
            },
            "typescript": {
                "demand": "high",
                "growth": "22%",
                "difficulty": "medium",
                "salary_impact": "12%",
            },
            "go": {
                "demand": "medium",
                "growth": "35%",
                "difficulty": "medium",
                "salary_impact": "20%",
            },
            "fastapi": {  # ADDED: FastAPI specific
                "demand": "high",
                "growth": "40%",
                "difficulty": "medium",
                "salary_impact": "15%",
            },
            "django": {  # ADDED: Django specific
                "demand": "high",
                "growth": "8%",
                "difficulty": "medium",
                "salary_impact": "12%",
            },
            "flask": {  # ADDED: Flask specific
                "demand": "medium",
                "growth": "5%",
                "difficulty": "low",
                "salary_impact": "8%",
            },
            "sqlalchemy": {  # ADDED: SQLAlchemy specific
                "demand": "medium",
                "growth": "10%",
                "difficulty": "medium",
                "salary_impact": "10%",
            },
        },
        "data_science": {
            "machine_learning": {
                "demand": "very_high",
                "growth": "22%",
                "difficulty": "high",
                "salary_impact": "25%",
            },
            "sql": {
                "demand": "very_high",
                "growth": "8%",
                "difficulty": "low",
                "salary_impact": "10%",
            },
            "tableau": {
                "demand": "high",
                "growth": "5%",
                "difficulty": "low",
                "salary_impact": "8%",
            },
            "tensorflow": {
                "demand": "high",
                "growth": "15%",
                "difficulty": "high",
                "salary_impact": "20%",
            },
            "pytorch": {
                "demand": "high",
                "growth": "25%",
                "difficulty": "high",
                "salary_impact": "22%",
            },
            "r": {
                "demand": "medium",
                "growth": "2%",
                "difficulty": "medium",
                "salary_impact": "5%",
            },
            "pandas": {
                "demand": "high",
                "growth": "12%",
                "difficulty": "medium",
                "salary_impact": "15%",
            },
            "scikit_learn": {
                "demand": "high",
                "growth": "18%",
                "difficulty": "medium",
                "salary_impact": "12%",
            },
        },
        "cloud": {
            "aws": {
                "demand": "very_high",
                "growth": "25%",
                "difficulty": "high",
                "salary_impact": "30%",
            },
            "azure": {
                "demand": "high",
                "growth": "20%",
                "difficulty": "high",
                "salary_impact": "25%",
            },
            "gcp": {
                "demand": "medium",
                "growth": "18%",
                "difficulty": "high",
                "salary_impact": "20%",
            },
            "terraform": {
                "demand": "high",
                "growth": "40%",
                "difficulty": "high",
                "salary_impact": "22%",
            },
            "openshift": {  # ADDED: OpenShift specific
                "demand": "medium",
                "growth": "15%",
                "difficulty": "high",
                "salary_impact": "18%",
            },
        },
    },
    "industry_standards": {
        "tech_company_requirements": {
            "startup": {
                "experience_flexibility": "high",
                "skill_over_degree": True,
                "growth_potential": "very_high",
                "typical_benefits": ["equity", "flexible_hours", "remote_work"],
                "culture_fit_importance": "very_high",
                "learning_curve_tolerance": "high",
            },
            "enterprise": {
                "experience_flexibility": "low",
                "formal_requirements": True,
                "stability": "high",
                "typical_benefits": ["health_insurance", "retirement", "training"],
                "culture_fit_importance": "medium",
                "learning_curve_tolerance": "medium",
            },
            "scale_up": {
                "experience_flexibility": "medium",
                "skill_over_degree": True,
                "growth_potential": "high",
                "typical_benefits": ["equity", "health_insurance", "flexible_hours"],
                "culture_fit_importance": "high",
                "learning_curve_tolerance": "medium",
            },
        },
        "experience_levels": {
            "junior": {
                "years": "0-2",
                "expectations": "mentorship_needed",
                "autonomy": "low",
            },
            "mid": {
                "years": "2-5",
                "expectations": "independent_work",
                "autonomy": "medium",
            },
            "senior": {
                "years": "5-8",
                "expectations": "mentoring_others",
                "autonomy": "high",
            },
            "lead": {
                "years": "8+",
                "expectations": "technical_leadership",
                "autonomy": "very_high",
            },
        },
    },
    "ats_optimization": {
        "critical_keywords": {
            "software_engineer": [
                "software development",
                "programming",
                "coding",
                "algorithms",
                "data structures",
                "version control",
                "testing",
                "debugging",
                "agile",
                "scrum",
                "git",
                "ci/cd",
                "code review",
            ],
            "backend_developer": [  # ADDED: Backend-specific keywords
                "python",
                "fastapi",
                "django",
                "flask",
                "sqlalchemy",
                "api development",
                "database design",
                "server architecture",
                "microservices",
                "rest api",
                "graphql",
                "sql",
                "nosql",
                "performance optimization",
                "security",
                "ci/cd",
                "testing",
                "linux",
                "docker",
                "kubernetes",
                "azure",
                "aws",
                "version control",
                "git",
            ],
            "python_developer": [  # ADDED: Python-specific keywords
                "python",
                "python 3",
                "fastapi",
                "django",
                "flask",
                "sqlalchemy",
                "rest api",
                "backend development",
                "database",
                "sql",
                "postgresql",
                "mysql",
                "testing",
                "pytest",
                "ci/cd",
                "linux",
                "docker",
                "git",
                "azure devops",
                "openshift",
                "rhel",
                "pyinstaller",
                "full-stack development",
                "system architecture",
                "automated testing",
                "incident management",
                "documentation",
                "stakeholder collaboration",
            ],
            "data_scientist": [
                "machine learning",
                "statistical analysis",
                "data mining",
                "predictive modeling",
                "data visualization",
                "big data",
                "python",
                "sql",
                "statistics",
                "experimentation",
                "a/b testing",
            ],
            "product_manager": [
                "product strategy",
                "roadmap",
                "stakeholder management",
                "user experience",
                "market research",
                "agile",
                "scrum",
                "analytics",
                "user stories",
                "requirements gathering",
            ],
            "frontend_developer": [
                "html",
                "css",
                "javascript",
                "react",
                "vue",
                "angular",
                "responsive design",
                "user interface",
                "web development",
                "typescript",
                "sass",
                "webpack",
            ],
            "devops_engineer": [
                "ci/cd",
                "automation",
                "infrastructure",
                "cloud computing",
                "containerization",
                "monitoring",
                "deployment",
                "scaling",
                "aws",
                "docker",
                "kubernetes",
                "terraform",
            ],
        },
        "red_flags": [
            "career gaps without explanation",
            "job hopping (5+ jobs in 3 years)",
            "overqualification for role",
            "missing required skills",
            "typos and grammatical errors",
            "generic objective statements",
            "outdated technologies only",
            "no quantifiable achievements",
        ],
        "green_flags": [
            "quantified achievements",
            "relevant side projects",
            "continuous learning evidence",
            "open source contributions",
            "clear career progression",
            "industry certifications",
            "leadership experience",
            "cross-functional collaboration",
        ],
    },
    "market_trends": {
        "2024_trends": {
            "remote_work": "35% of tech jobs now remote-first",
            "ai_skills": "40% increase in AI-related job postings",
            "cybersecurity": "Growing 25% annually",
            "sustainability": "Green tech roles up 50%",
            "blockchain": "Declining demand, down 30%",
            "mobile_development": "Stable demand, slight growth",
            "python_development": "Consistently high demand, 15% growth",
            "fastapi_adoption": "Rapid growth, 40% increase in job postings",
        },
        "hiring_practices": {
            "technical_interviews": "Still standard for 80% of tech roles",
            "portfolio_importance": "60% of employers check GitHub/portfolio",
            "cultural_fit": "Increasingly important factor",
            "remote_interviews": "90% now conducted remotely",
            "coding_challenges": "Take-home preferred over whiteboard",
        },
        "skill_priorities": {
            "technical_skills": "60% of evaluation",
            "soft_skills": "25% of evaluation",
            "cultural_fit": "15% of evaluation",
        },
    },
}

HIRING_INSIGHTS = [
    "Python developers with FastAPI experience command 15-20% higher salaries",
    "Backend developers with cloud experience (Azure/AWS) are highly sought after",
    "Full-stack Python developers have 30% more job opportunities",
    "Software engineers with Python and AWS experience command 20-30% higher salaries",
    "Startups value adaptability and learning ability over specific technology experience",
    "ATS systems prioritize exact keyword matches in the first screening round",
    "Remote work experience is now a significant advantage for most tech positions",
    "Data science roles require strong communication skills, not just technical abilities",
    "Product management roles value cross-functional experience highly",
    "Career gaps can be explained positively with learning/upskilling activities",
    "GitHub contributions are more valuable than certificates for developer roles",
    "DevOps experience is becoming essential for senior developer positions",
    "Companies prefer T-shaped professionals: deep in one area, broad in others",
    "Industry certifications matter more in enterprise environments than startups",
    "Portfolio projects should demonstrate real-world problem solving",
    "Salary negotiations are more successful with market data and competing offers",
    "Technical leadership skills become crucial after 5+ years of experience",
    "Open source contributions significantly boost hiring chances for developers",
    "CI/CD pipeline experience is now expected for most backend roles",
    "Docker and containerization knowledge is becoming standard requirement",
]
